### ISSUE TITLE
Difference between Playerkit 1.08k & Playerkit 2.8

### ISSUE THREAD

**Issue by Shanl3y** [GothicFixTeam/GothicFix#4]
Hi, I would like to know the difference between "gothic1_playerkit-1.08k.exe" and "Gothic1_PlayerKit-2.8.exe". I'm confused because a lot of guides recommend to install both. Although 1.08k seems to be the older version.

Also there's the 'gothic2_playerkit-2.6f.exe' and ' Gothic2_PlayerKit-2.8.exe'. What's the difference between those?

**Comment by MaGoth** [comment]
> Hi, I would like to know the difference between "gothic1_playerkit-1.08k.exe" and "Gothic1_PlayerKit-2.8.exe". I'm confused because a lot of guides recommend to install both. Although 1.08k seems to be the older version.
>
Hi Shanl3y,
1. the difference is in fixing some bugs of the old version, adding support for other languages and parameters from Systempack.ini in ini-files of mods.
2. Both must be installed because when installing the original version of "gothic1_playerkit-1.08k.exe" its exe file is checked, the same happens when installing "Gothic1_PlayerKit-2.8.exe".

> Also there's the 'gothic2_playerkit-2.6f.exe' and ' Gothic2_PlayerKit-2.8.exe'. What's the difference between those?

The differences are the same as in points 1, 2 above.

**Comment by Shanl3y** [comment]
Thank you! This helped me out a lot!
